# Enable or disable debugging
debug: false

# Time it takes to charge up a jump in ticks
# 1 second = 20 ticks
# default = 60 ticks = 3 seconds
chargeup-ticks: 60

# Elytra gliding speed multiplier
# default = 1.0
speed-multiplier: 1.0

# Launch strength multiplier
# default = 1.0
launch-multiplier: 1.0

# throwing an enderpearl while flying boosts your velocity by this amount
enderpearl-velocity-multiplier: 1.3
# maximum velocity after which enderpearls stop working
enderpearl-max-velocity: 5
# enderpearl use delay in ticks
enderpearl-use-delay: 30

# How many points of XP to use per point of elytra damage
elytra-xp-per-damage: 10

# True if enhanced flight is to be enabled by default, else false
# default = true
default-enhanced-flight: true

# Messages sent to players. You can use &0..&f color codes.
# All messages starting with error-* have the prefix automatically added in front.
# When rewriting messages that contain text like %d and %s make sure you keep it.
messages:
  need-player: '&4[SuperElytra]&r Only players can toggle their elytra mode.'
  usage: '&4Usage: /elytramode (normal|super)'
  enabled: '&9[SuperElytra]&r You enabled enhanced flight'
  disabled: '&9[SuperElytra]&r You disabled enhanced flight'
  configuration-loaded: '&6Configuration loaded.'
